//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirst_Prosedurlu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Db_first_uygulama2Entities : DbContext
    {
        public Db_first_uygulama2Entities()
            : base("name=Db_first_uygulama2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Musteriler> Musterilers { get; set; }
    
        public virtual ObjectResult<MAd_Ara_Result> MAd_Ara(string adara)
        {
            var adaraParameter = adara != null ?
                new ObjectParameter("adara", adara) :
                new ObjectParameter("adara", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MAd_Ara_Result>("MAd_Ara", adaraParameter);
        }
    
        public virtual int MGuncelle(Nullable<int> id, string adsoyad, string tc, string urun, Nullable<decimal> fiyat)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var adsoyadParameter = adsoyad != null ?
                new ObjectParameter("adsoyad", adsoyad) :
                new ObjectParameter("adsoyad", typeof(string));
    
            var tcParameter = tc != null ?
                new ObjectParameter("tc", tc) :
                new ObjectParameter("tc", typeof(string));
    
            var urunParameter = urun != null ?
                new ObjectParameter("urun", urun) :
                new ObjectParameter("urun", typeof(string));
    
            var fiyatParameter = fiyat.HasValue ?
                new ObjectParameter("fiyat", fiyat) :
                new ObjectParameter("fiyat", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MGuncelle", idParameter, adsoyadParameter, tcParameter, urunParameter, fiyatParameter);
        }
    
        public virtual int MKaydet(string adsoyad, string tc, string urun, Nullable<decimal> fiyat)
        {
            var adsoyadParameter = adsoyad != null ?
                new ObjectParameter("adsoyad", adsoyad) :
                new ObjectParameter("adsoyad", typeof(string));
    
            var tcParameter = tc != null ?
                new ObjectParameter("tc", tc) :
                new ObjectParameter("tc", typeof(string));
    
            var urunParameter = urun != null ?
                new ObjectParameter("urun", urun) :
                new ObjectParameter("urun", typeof(string));
    
            var fiyatParameter = fiyat.HasValue ?
                new ObjectParameter("fiyat", fiyat) :
                new ObjectParameter("fiyat", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MKaydet", adsoyadParameter, tcParameter, urunParameter, fiyatParameter);
        }
    
        public virtual ObjectResult<MListele_Result> MListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MListele_Result>("MListele");
        }
    
        public virtual int MSil(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSil", idParameter);
        }
    }
}
