//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirst_Prosedurlu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public int id { get; set; }
        public string AdSoyad { get; set; }
        public string Tc { get; set; }
        public string Urun { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
    }
}
